version: '3'
services:
  web:
    image: 332210366174.dkr.ecr.eu-west-2.amazonaws.com/colab-codes
    ports:
      - "80:5000"
    logging:
      driver: awslogs
      options:
        awslogs-group: colab-codes
        awslogs-region: eu-west-2
        awslogs-stream-prefix: web